// Every theme maps to the same set of CSS variables so any component
// automatically re-skins itself when the active theme changes.
export const THEMES = {
  cottonCandy: {
    label: "Cotton Candy",
    swatch: ["#ffcbcb", "#ffa7a7", "#c9fdff", "#dffeff"],
    vars: {
      "--bg": "#fff4f4",
      "--surface": "#ffffff",
      "--card": "#ffcbcb",
      "--card2": "#c9fdff",
      "--accent": "#ffa7a7",
      "--accent2": "#dffeff",
      "--text": "#4a3535",
      "--text-soft": "#8a6c6c",
      "--border": "#ffcbcb",
    },
  },
  monochrome: {
    label: "Black & White",
    swatch: ["#000000", "#3a3a3a", "#e5e5e5", "#ffffff"],
    vars: {
      "--bg": "#ffffff",
      "--surface": "#f5f5f5",
      "--card": "#ffffff",
      "--card2": "#e5e5e5",
      "--accent": "#000000",
      "--accent2": "#666666",
      "--text": "#111111",
      "--text-soft": "#555555",
      "--border": "#111111",
    },
  },
  sunsetEmber: {
    label: "Sunset Ember",
    swatch: ["#FFFAF3", "#FFF2DB", "#FFE5BF", "#F62440"],
    vars: {
      "--bg": "#FFFAF3",
      "--surface": "#FFF2DB",
      "--card": "#FFE5BF",
      "--card2": "#FFF2DB",
      "--accent": "#F62440",
      "--accent2": "#FFE5BF",
      "--text": "#3a1414",
      "--text-soft": "#8a5a5a",
      "--border": "#FFE5BF",
    },
  },
  royalViolet: {
    label: "Royal Violet",
    swatch: ["#333D6D", "#723EC3", "#FFCF95", "#FFF0D9"],
    vars: {
      "--bg": "#FFF0D9",
      "--surface": "#fff8ec",
      "--card": "#FFCF95",
      "--card2": "#e4defc",
      "--accent": "#723EC3",
      "--accent2": "#333D6D",
      "--text": "#2a1f4d",
      "--text-soft": "#333D6D",
      "--border": "#FFCF95",
    },
  },
  electricSky: {
    label: "Electric Sky",
    swatch: ["#5409DA", "#4E71FF", "#8DD8FF", "#BBFBFF"],
    vars: {
      "--bg": "#BBFBFF",
      "--surface": "#e3fdff",
      "--card": "#8DD8FF",
      "--card2": "#c7ecff",
      "--accent": "#4E71FF",
      "--accent2": "#5409DA",
      "--text": "#1a1550",
      "--text-soft": "#33409e",
      "--border": "#8DD8FF",
    },
  },
  mauveBerry: {
    label: "Mauve Berry",
    swatch: ["#5D3140", "#CF4173", "#F39399", "#F6D8BD"],
    vars: {
      "--bg": "#F6D8BD",
      "--surface": "#fae6d2",
      "--card": "#F39399",
      "--card2": "#f0c3c6",
      "--accent": "#CF4173",
      "--accent2": "#5D3140",
      "--text": "#3a1420",
      "--text-soft": "#5D3140",
      "--border": "#F39399",
    },
  },
  tropicalPop: {
    label: "Tropical Pop",
    swatch: ["#70FFD2", "#FFFC8C", "#FFCC4D", "#FF9137"],
    vars: {
      "--bg": "#FFFC8C",
      "--surface": "#fffde0",
      "--card": "#70FFD2",
      "--card2": "#FFCC4D",
      "--accent": "#FF9137",
      "--accent2": "#FFCC4D",
      "--text": "#3a2a00",
      "--text-soft": "#7a5c1a",
      "--border": "#70FFD2",
    },
  },
};

export const THEME_ORDER = [
  "cottonCandy",
  "monochrome",
  "sunsetEmber",
  "royalViolet",
  "electricSky",
  "mauveBerry",
  "tropicalPop",
];
